<?php

return [
    'AF' => ['label' => 'Afghanistan', 'code' => '+93'],
    'AX' => ['label' => 'Åland Islands', 'code' => '+35818'],
    'AL' => ['label' => 'Albania', 'code' => '+355'],
    'DZ' => ['label' => 'Algeria', 'code' => '+213'],
    'AS' => ['label' => 'American Samoa', 'code' => '+1684'],
    'AD' => ['label' => 'Andorra', 'code' => '+376'],
    'AO' => ['label' => 'Angola', 'code' => '+244'],
    'AI' => ['label' => 'Anguilla', 'code' => '+1264'],
    'AQ' => ['label' => 'Antarctica', 'code' => ''],
    'AG' => ['label' => 'Antigua and Barbuda', 'code' => '+1268'],
    'AR' => ['label' => 'Argentina', 'code' => '+54'],
    'AM' => ['label' => 'Armenia', 'code' => '+374'],
    'AW' => ['label' => 'Aruba', 'code' => '+297'],
    'AU' => ['label' => 'Australia', 'code' => '+61'],
    'AT' => ['label' => 'Austria', 'code' => '+43'],
    'AZ' => ['label' => 'Azerbaijan', 'code' => '+994'],
    'BS' => ['label' => 'Bahamas', 'code' => '+1242'],
    'BH' => ['label' => 'Bahrain', 'code' => '+973'],
    'BD' => ['label' => 'Bangladesh', 'code' => '+880'],
    'BB' => ['label' => 'Barbados', 'code' => '+1246'],
    'BY' => ['label' => 'Belarus', 'code' => '+375'],
    'BE' => ['label' => 'Belgium', 'code' => '+32'],
    'BZ' => ['label' => 'Belize', 'code' => '+501'],
    'BJ' => ['label' => 'Benin', 'code' => '+229'],
    'BM' => ['label' => 'Bermuda', 'code' => '+1441'],
    'BT' => ['label' => 'Bhutan', 'code' => '+975'],
    'BO' => ['label' => 'Bolivia', 'code' => '+591'],
    'BA' => ['label' => 'Bosnia and Herzegovina', 'code' => '+387'],
    'BW' => ['label' => 'Botswana', 'code' => '+267'],
    'BV' => ['label' => 'Bouvet Island', 'code' => '+47'],
    'BR' => ['label' => 'Brazil', 'code' => '+55'],
    'IO' => ['label' => 'British Indian Ocean Territory', 'code' => '+246'],
    'VG' => ['label' => 'British Virgin Islands', 'code' => '+1284'],
    'BN' => ['label' => 'Brunei', 'code' => '+673'],
    'BG' => ['label' => 'Bulgaria', 'code' => '+359'],
    'BF' => ['label' => 'Burkina Faso', 'code' => '+226'],
    'BI' => ['label' => 'Burundi', 'code' => '+257'],
    'KH' => ['label' => 'Cambodia', 'code' => '+855'],
    'CM' => ['label' => 'Cameroon', 'code' => '+237'],
    'CA' => ['label' => 'Canada', 'code' => '+1'],
    'CV' => ['label' => 'Cape Verde', 'code' => '+238'],
    'BQ' => ['label' => 'Caribbean Netherlands', 'code' => '+599'],
    'KY' => ['label' => 'Cayman Islands', 'code' => '+1345'],
    'CF' => ['label' => 'Central African Republic', 'code' => '+236'],
    'TD' => ['label' => 'Chad', 'code' => '+235'],
    'CL' => ['label' => 'Chile', 'code' => '+56'],
    'CN' => ['label' => 'China', 'code' => '+86'],
    'CX' => ['label' => 'Christmas Island', 'code' => '+61'],
    'CC' => ['label' => 'Cocos (Keeling) Islands', 'code' => '+61'],
    'CO' => ['label' => 'Colombia', 'code' => '+57'],
    'KM' => ['label' => 'Comoros', 'code' => '+269'],
    'CK' => ['label' => 'Cook Islands', 'code' => '+682'],
    'CR' => ['label' => 'Costa Rica', 'code' => '+506'],
    'HR' => ['label' => 'Croatia', 'code' => '+385'],
    'CU' => ['label' => 'Cuba', 'code' => '+53'],
    'CW' => ['label' => 'Curaçao', 'code' => '+599'],
    'CY' => ['label' => 'Cyprus', 'code' => '+357'],
    'CZ' => ['label' => 'Czechia', 'code' => '+420'],
    'DK' => ['label' => 'Denmark', 'code' => '+45'],
    'DJ' => ['label' => 'Djibouti', 'code' => '+253'],
    'DM' => ['label' => 'Dominica', 'code' => '+1767'],
    'DO' => ['label' => 'Dominican Republic', 'code' => '+1809'],
    'CD' => ['label' => 'DR Congo', 'code' => '+243'],
    'EC' => ['label' => 'Ecuador', 'code' => '+593'],
    'EG' => ['label' => 'Egypt', 'code' => '+20'],
    'SV' => ['label' => 'El Salvador', 'code' => '+503'],
    'GQ' => ['label' => 'Equatorial Guinea', 'code' => '+240'],
    'ER' => ['label' => 'Eritrea', 'code' => '+291'],
    'EE' => ['label' => 'Estonia', 'code' => '+372'],
    'SZ' => ['label' => 'Eswatini', 'code' => '+268'],
    'ET' => ['label' => 'Ethiopia', 'code' => '+251'],
    'FK' => ['label' => 'Falkland Islands', 'code' => '+500'],
    'FO' => ['label' => 'Faroe Islands', 'code' => '+298'],
    'FJ' => ['label' => 'Fiji', 'code' => '+679'],
    'FI' => ['label' => 'Finland', 'code' => '+358'],
    'FR' => ['label' => 'France', 'code' => '+33'],
    'GF' => ['label' => 'French Guiana', 'code' => '+594'],
    'PF' => ['label' => 'French Polynesia', 'code' => '+689'],
    'TF' => ['label' => 'French Southern and Antarctic Lands', 'code' => '+262'],
    'GA' => ['label' => 'Gabon', 'code' => '+241'],
    'GM' => ['label' => 'Gambia', 'code' => '+220'],
    'GE' => ['label' => 'Georgia', 'code' => '+995'],
    'DE' => ['label' => 'Germany', 'code' => '+49'],
    'GH' => ['label' => 'Ghana', 'code' => '+233'],
    'GI' => ['label' => 'Gibraltar', 'code' => '+350'],
    'GR' => ['label' => 'Greece', 'code' => '+30'],
    'GL' => ['label' => 'Greenland', 'code' => '+299'],
    'GD' => ['label' => 'Grenada', 'code' => '+1473'],
    'GP' => ['label' => 'Guadeloupe', 'code' => '+590'],
    'GU' => ['label' => 'Guam', 'code' => '+1671'],
    'GT' => ['label' => 'Guatemala', 'code' => '+502'],
    'GG' => ['label' => 'Guernsey', 'code' => '+44'],
    'GN' => ['label' => 'Guinea', 'code' => '+224'],
    'GW' => ['label' => 'Guinea-Bissau', 'code' => '+245'],
    'GY' => ['label' => 'Guyana', 'code' => '+592'],
    'HT' => ['label' => 'Haiti', 'code' => '+509'],
    'HM' => ['label' => 'Heard Island and McDonald Islands', 'code' => ''],
    'HN' => ['label' => 'Honduras', 'code' => '+504'],
    'HK' => ['label' => 'Hong Kong', 'code' => '+852'],
    'HU' => ['label' => 'Hungary', 'code' => '+36'],
    'IS' => ['label' => 'Iceland', 'code' => '+354'],
    'IN' => ['label' => 'India', 'code' => '+91'],
    'ID' => ['label' => 'Indonesia', 'code' => '+62'],
    'IR' => ['label' => 'Iran', 'code' => '+98'],
    'IQ' => ['label' => 'Iraq', 'code' => '+964'],
    'IE' => ['label' => 'Ireland', 'code' => '+353'],
    'IM' => ['label' => 'Isle of Man', 'code' => '+44'],
    'IL' => ['label' => 'Israel', 'code' => '+972'],
    'IT' => ['label' => 'Italy', 'code' => '+39'],
    'CI' => ['label' => 'Ivory Coast', 'code' => '+225'],
    'JM' => ['label' => 'Jamaica', 'code' => '+1876'],
    'JP' => ['label' => 'Japan', 'code' => '+81'],
    'JE' => ['label' => 'Jersey', 'code' => '+44'],
    'JO' => ['label' => 'Jordan', 'code' => '+962'],
    'KZ' => ['label' => 'Kazakhstan', 'code' => '+76'],
    'KE' => ['label' => 'Kenya', 'code' => '+254'],
    'KI' => ['label' => 'Kiribati', 'code' => '+686'],
    'XK' => ['label' => 'Kosovo', 'code' => '+383'],
    'KW' => ['label' => 'Kuwait', 'code' => '+965'],
    'KG' => ['label' => 'Kyrgyzstan', 'code' => '+996'],
    'LA' => ['label' => 'Laos', 'code' => '+856'],
    'LV' => ['label' => 'Latvia', 'code' => '+371'],
    'LB' => ['label' => 'Lebanon', 'code' => '+961'],
    'LS' => ['label' => 'Lesotho', 'code' => '+266'],
    'LR' => ['label' => 'Liberia', 'code' => '+231'],
    'LY' => ['label' => 'Libya', 'code' => '+218'],
    'LI' => ['label' => 'Liechtenstein', 'code' => '+423'],
    'LT' => ['label' => 'Lithuania', 'code' => '+370'],
    'LU' => ['label' => 'Luxembourg', 'code' => '+352'],
    'MO' => ['label' => 'Macau', 'code' => '+853'],
    'MG' => ['label' => 'Madagascar', 'code' => '+261'],
    'MW' => ['label' => 'Malawi', 'code' => '+265'],
    'MY' => ['label' => 'Malaysia', 'code' => '+60'],
    'MV' => ['label' => 'Maldives', 'code' => '+960'],
    'ML' => ['label' => 'Mali', 'code' => '+223'],
    'MT' => ['label' => 'Malta', 'code' => '+356'],
    'MH' => ['label' => 'Marshall Islands', 'code' => '+692'],
    'MQ' => ['label' => 'Martinique', 'code' => '+596'],
    'MR' => ['label' => 'Mauritania', 'code' => '+222'],
    'MU' => ['label' => 'Mauritius', 'code' => '+230'],
    'YT' => ['label' => 'Mayotte', 'code' => '+262'],
    'MX' => ['label' => 'Mexico', 'code' => '+52'],
    'FM' => ['label' => 'Micronesia', 'code' => '+691'],
    'MD' => ['label' => 'Moldova', 'code' => '+373'],
    'MC' => ['label' => 'Monaco', 'code' => '+377'],
    'MN' => ['label' => 'Mongolia', 'code' => '+976'],
    'ME' => ['label' => 'Montenegro', 'code' => '+382'],
    'MS' => ['label' => 'Montserrat', 'code' => '+1664'],
    'MA' => ['label' => 'Morocco', 'code' => '+212'],
    'MZ' => ['label' => 'Mozambique', 'code' => '+258'],
    'MM' => ['label' => 'Myanmar', 'code' => '+95'],
    'NA' => ['label' => 'Namibia', 'code' => '+264'],
    'NR' => ['label' => 'Nauru', 'code' => '+674'],
    'NP' => ['label' => 'Nepal', 'code' => '+977'],
    'NL' => ['label' => 'Netherlands', 'code' => '+31'],
    'NC' => ['label' => 'New Caledonia', 'code' => '+687'],
    'NZ' => ['label' => 'New Zealand', 'code' => '+64'],
    'NI' => ['label' => 'Nicaragua', 'code' => '+505'],
    'NE' => ['label' => 'Niger', 'code' => '+227'],
    'NG' => ['label' => 'Nigeria', 'code' => '+234'],
    'NU' => ['label' => 'Niue', 'code' => '+683'],
    'NF' => ['label' => 'Norfolk Island', 'code' => '+672'],
    'KP' => ['label' => 'North Korea', 'code' => '+850'],
    'MK' => ['label' => 'North Macedonia', 'code' => '+389'],
    'MP' => ['label' => 'Northern Mariana Islands', 'code' => '+1670'],
    'NO' => ['label' => 'Norway', 'code' => '+47'],
    'OM' => ['label' => 'Oman', 'code' => '+968'],
    'PK' => ['label' => 'Pakistan', 'code' => '+92'],
    'PW' => ['label' => 'Palau', 'code' => '+680'],
    'PS' => ['label' => 'Palestine', 'code' => '+970'],
    'PA' => ['label' => 'Panama', 'code' => '+507'],
    'PG' => ['label' => 'Papua New Guinea', 'code' => '+675'],
    'PY' => ['label' => 'Paraguay', 'code' => '+595'],
    'PE' => ['label' => 'Peru', 'code' => '+51'],
    'PH' => ['label' => 'Philippines', 'code' => '+63'],
    'PN' => ['label' => 'Pitcairn Islands', 'code' => '+64'],
    'PL' => ['label' => 'Poland', 'code' => '+48'],
    'PT' => ['label' => 'Portugal', 'code' => '+351'],
    'PR' => ['label' => 'Puerto Rico', 'code' => '+1787'],
    'QA' => ['label' => 'Qatar', 'code' => '+974'],
    'CG' => ['label' => 'Republic of the Congo', 'code' => '+242'],
    'RE' => ['label' => 'Réunion', 'code' => '+262'],
    'RO' => ['label' => 'Romania', 'code' => '+40'],
    'RU' => ['label' => 'Russia', 'code' => '+73'],
    'RW' => ['label' => 'Rwanda', 'code' => '+250'],
    'BL' => ['label' => 'Saint Barthélemy', 'code' => '+590'],
    'SH' => ['label' => 'Saint Helena, Ascension and Tristan da Cunha', 'code' => '+290'],
    'KN' => ['label' => 'Saint Kitts and Nevis', 'code' => '+1869'],
    'LC' => ['label' => 'Saint Lucia', 'code' => '+1758'],
    'MF' => ['label' => 'Saint Martin', 'code' => '+590'],
    'PM' => ['label' => 'Saint Pierre and Miquelon', 'code' => '+508'],
    'VC' => ['label' => 'Saint Vincent and the Grenadines', 'code' => '+1784'],
    'WS' => ['label' => 'Samoa', 'code' => '+685'],
    'SM' => ['label' => 'San Marino', 'code' => '+378'],
    'ST' => ['label' => 'São Tomé and Príncipe', 'code' => '+239'],
    'SA' => ['label' => 'Saudi Arabia', 'code' => '+966'],
    'SN' => ['label' => 'Senegal', 'code' => '+221'],
    'RS' => ['label' => 'Serbia', 'code' => '+381'],
    'SC' => ['label' => 'Seychelles', 'code' => '+248'],
    'SL' => ['label' => 'Sierra Leone', 'code' => '+232'],
    'SG' => ['label' => 'Singapore', 'code' => '+65'],
    'SX' => ['label' => 'Sint Maarten', 'code' => '+1721'],
    'SK' => ['label' => 'Slovakia', 'code' => '+421'],
    'SI' => ['label' => 'Slovenia', 'code' => '+386'],
    'SB' => ['label' => 'Solomon Islands', 'code' => '+677'],
    'SO' => ['label' => 'Somalia', 'code' => '+252'],
    'ZA' => ['label' => 'South Africa', 'code' => '+27'],
    'GS' => ['label' => 'South Georgia', 'code' => '+500'],
    'KR' => ['label' => 'South Korea', 'code' => '+82'],
    'SS' => ['label' => 'South Sudan', 'code' => '+211'],
    'ES' => ['label' => 'Spain', 'code' => '+34'],
    'LK' => ['label' => 'Sri Lanka', 'code' => '+94'],
    'SD' => ['label' => 'Sudan', 'code' => '+249'],
    'SR' => ['label' => 'Suriname', 'code' => '+597'],
    'SJ' => ['label' => 'Svalbard and Jan Mayen', 'code' => '+4779'],
    'SE' => ['label' => 'Sweden', 'code' => '+46'],
    'CH' => ['label' => 'Switzerland', 'code' => '+41'],
    'SY' => ['label' => 'Syria', 'code' => '+963'],
    'TW' => ['label' => 'Taiwan', 'code' => '+886'],
    'TJ' => ['label' => 'Tajikistan', 'code' => '+992'],
    'TZ' => ['label' => 'Tanzania', 'code' => '+255'],
    'TH' => ['label' => 'Thailand', 'code' => '+66'],
    'TL' => ['label' => 'Timor-Leste', 'code' => '+670'],
    'TG' => ['label' => 'Togo', 'code' => '+228'],
    'TK' => ['label' => 'Tokelau', 'code' => '+690'],
    'TO' => ['label' => 'Tonga', 'code' => '+676'],
    'TT' => ['label' => 'Trinidad and Tobago', 'code' => '+1868'],
    'TN' => ['label' => 'Tunisia', 'code' => '+216'],
    'TR' => ['label' => 'Turkey', 'code' => '+90'],
    'TM' => ['label' => 'Turkmenistan', 'code' => '+993'],
    'TC' => ['label' => 'Turks and Caicos Islands', 'code' => '+1649'],
    'TV' => ['label' => 'Tuvalu', 'code' => '+688'],
    'UG' => ['label' => 'Uganda', 'code' => '+256'],
    'UA' => ['label' => 'Ukraine', 'code' => '+380'],
    'AE' => ['label' => 'United Arab Emirates', 'code' => '+971'],
    'GB' => ['label' => 'United Kingdom', 'code' => '+44'],
    'US' => ['label' => 'United States', 'code' => '+1201'],
    'UM' => ['label' => 'United States Minor Outlying Islands', 'code' => '+268'],
    'VI' => ['label' => 'United States Virgin Islands', 'code' => '+1340'],
    'UY' => ['label' => 'Uruguay', 'code' => '+598'],
    'UZ' => ['label' => 'Uzbekistan', 'code' => '+998'],
    'VU' => ['label' => 'Vanuatu', 'code' => '+678'],
    'VA' => ['label' => 'Vatican City', 'code' => '+3906698'],
    'VE' => ['label' => 'Venezuela', 'code' => '+58'],
    'VN' => ['label' => 'Vietnam', 'code' => '+84'],
    'WF' => ['label' => 'Wallis and Futuna', 'code' => '+681'],
    'EH' => ['label' => 'Western Sahara', 'code' => '+2125288'],
    'YE' => ['label' => 'Yemen', 'code' => '+967'],
    'ZM' => ['label' => 'Zambia', 'code' => '+260'],
    'ZW' => ['label' => 'Zimbabwe', 'code' => '+263'],
];

